title: "Mon parcours en Data Science"
description: "Voici mon portfolio de projets de Data Science en Santé <br> <br> Perrine Warter"
author : Perrine Warter 
url :  "https://perrinewtr.github.io/Portfolio/"
theme: jekyll-theme-tactile

